spring:
  datasource:
    url: jdbc:mysql://81.68.225.220:3307/task
    username: root
    password: Pyh.794.pyh

  data:
    redis:
      host: 81.68.225.220
      port: 6888
      password: Qrf.805.qrf
      database: 0


server:
  port: 8080
  address: 0.0.0.0

mybatis:
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: U0FTVF9Gb3JldmVy #JWT 密钥
  expiration: 864000000
